# -*- coding: utf-8 -*-
"""Regresi Polinomial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zEyrHprP-8Ccjb9g9yKwIA1GXr2mZM3D
"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
import numpy as np

#Database
# x = Data, y = Target
x = [[2],[3],[4],[5],[6],[7],[8],[9],[10],[11]]
y = [4, 9, 16, 25, 36, 49, 64, 81, 100, 121]

#Data uji
predict = np.array([[15]])
poly = PolynomialFeatures(degree=2)
x_=poly.fit_transform(x)
predict_ = poly.fit_transform(predict)
regr = linear_model.LinearRegression()
regr.fit(x_,y)

#Menampilkan data prediksi
print("Prediksi")
print("Input = ", predict)
print("Output = ", regr.predict(predict_))