# -*- coding: utf-8 -*-
"""Regresi Linear Fiskom

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pVxk3S3vbNnMDjrlyNgJCo0IcbJPg6W
"""

import numpy as np
from sklearn.linear_model import LinearRegression

#Database
# x = Data, y = Target
x = [[2],[3],[4],[5],[6],[7],[8],[9],[10],[11]]
y = [6, 9, 12, 15, 18,21,24,27,30,33]

regr = LinearRegression().fit(x,y)
regr.score(x, y)

#Data uji
predict = np.array([[17]])

#Menampilkan data prediksi
print("Prediksi")
print("Input = ", predict)
print("Output = ", regr.predict(predict))